kinds:
  misc:
    template: '{prefix} {type} {title}, {section} : {organization} : {start}'
    morphs:
      - type
      - organization
  conf:
    template: '{prefix} "{topic}" : {author} : {title}, {organization} : {start}'
    morphs:
      - organization
  mastersthesis:
    template: '{type} "{title}" : {author} : {school}, {address}, {year}'
sort:
  field: end
  reversed: true
group:
  is_entry_type: true
  is_field: false
  field: "organization"
